---
- name: Listen for events on a webhook from CheckMK
  hosts: all
  sources:
    - name: Listen for alerts from CheckMK
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 4999

  rules:
    - name: Web Server Down Detected
      condition: event.payload.event_title == "[Triggered] Systemd Service httpd CRITICAL"
      action:
        run_workflow_template:
          name: "CheckMK httpd service down"
          organization: "Default"
          job_args:
            extra_vars:
              checkmk_hostname: "{{ event.payload.hostname }}"
              checkmk_message: "{{ event.payload.message }}"
          retries: 1
          delay: 1
